import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Ticket !</title>
        <meta name="description" content="Generated by create next app" />
        <a rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://wishwork.org/">WishWork Ticketing System!</a>
        </h1>

        <p className={styles.description}>
          this site is under construction
        </p>

        <div className={styles.grid}>
          <Link href="/tickets" className={styles.card} >
            <h2>New Ticket &rarr;</h2>
            <p>Create a ticket and ask any.</p>
          </Link>

          <Link href="/tickets" className={styles.card} >
            <h2>List Tickets &rarr;</h2>
            <p>All Tickets are here.</p>
          </Link>

          <a
            href="https://wishwork.org/"
            className={styles.card}
            >
            <h2>WishWork &rarr;</h2>
            <p>Discover and develop your community with WishWork ticketing system.</p>
          </a>

          <a
            href="https://wishwork.org/"
            className={styles.card}
            >
            <h2>Contact us &rarr;</h2>
            <p>
              By visiting out website you can be in touch.
            </p>
            <p>
              2021
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
          >
          <span className={styles.logo}>
            WishWork Ltd
          </span>
        </a>
      </footer>
    </div>
  )
}
